apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: bG9rZXNo
  password: YWRtaW4xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      args:
      - "env"
      envFrom:
      - secretRef:
          name: "app-secret"
    