apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: |
    bG9rZXNo
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: secret-volume
      mountPath: /lokesh/data
    args:
    - "sleep"
    - "3600"
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret