apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pod-volume
      mountPath: /lokesh/data
  volumes:
  - name: pod-volume
    persistentVolumeClaim:
      claimName: my-pvc