kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
  - role: control-plane
    extraPortMappings:  # Map kind docker port to machine port to test NodePort Service Type
    - containerPort: 30001
      hostPort: 30001
      protocol: TCP
  - role: worker
  - role: worker
