apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      args:
        - "/bin/sh"
        - "-c"
        - "echo My Path is: $PATH"