apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
  containers:
    - name: ubuntu
      image: ubuntu
      args:
        - "sleep"
        - "3600"