apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu
      image: ubuntu
      env:
        - name: "spring.profiles.active"
          value: "dev"
        - name: "timeout"
          value: "80s"
      args:
        - "env"